export const DATA = [
	{
		id: '1',
		uri: '../../assets/Images/image_17.png',
		name: 'Virat Kholi',
		position: 'Batsman',
		nationalTeam: 'India',
		iplTeam: 'RCB',
		stockPrice: '₹5,500',
		percentaChange: '95%',
	},
	{
		id: '2',
		uri: '../../assets/Images/image_17.png',
		name: 'Virat Kholi',
		position: 'Batsman',
		nationalTeam: 'India',
		iplTeam: 'RCB',
		stockPrice: '₹5,500',
		percentaChange: '95%',
	},
	{
		id: '3',
		uri: '../../assets/Images/image_17.png',
		name: 'Virat Kholi',
		position: 'Batsman',
		nationalTeam: 'India',
		iplTeam: 'RCB',
		stockPrice: '₹5,500',
		percentaChange: '95%',
	},
	{
		id: '4',
		uri: '../../assets/Images/image_17.png',
		name: 'Virat Kholi',
		position: 'Batsman',
		nationalTeam: 'India',
		iplTeam: 'RCB',
		stockPrice: '₹5,500',
		percentaChange: '95%',
	},
]
